steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']
  - name: python  
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]  
  # - name: "gcr.io/cloud-builders/python"
  #   entrypoint: python
  #   args:
  #     - "app/manage.py"
  #     - "migrate"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      service nginx restart
      service restart gunicorn