steps:
  - name: "git"
    args: ["clone", "https://github.com/nikhilkotiya/Elevator_problem.git", "app"]
  - name: python  
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]  
  # - name: "gcr.io/cloud-builders/python"
  #   entrypoint: python
  #   args:
  #     - "app/manage.py"
  #     - "migrate"
  - name: "bash"
    entrypoint: bash
    args:
      - "-c"
      - |
        sudo systemctl restart nginx
        sudo systemctl restart gunicorn
