steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/nikhilkotiya/Elevator_problem.git", "app"]
  - name: "gcr.io/cloud-builders/python"
    entrypoint: pip
    args: ["install", "-r", "app/requirements.txt"]
  - name: "gcr.io/cloud-builders/python"
    entrypoint: python
    args:
      - "app/manage.py"
      - "migrate"
  - name: "gcr.io/cloud-builders/bash"
    entrypoint: bash
    args:
      - "-c"
      - |
        sudo systemctl restart nginx
        sudo systemctl restart gunicorn
