steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/nikhilkotiya/Elevator_problem.git", "/workspace/Elevator_problem"]
  - name: "ubuntu"
    entrypoint: bash
    args:
      - "-c"
      - |
        deploy.yml

  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args:
  #   - '-eEuo'
  #   - 'pipefail'
  #   - '-c'
  #   - |-
  #     systemctl restart gunicorn
  #     systemctl restart nginx