steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']
  - name: python  
    entrypoint: python
    args: ["-m", "pip", "install", "--upgrade", "pip"]  
  # - name: "gcr.io/cloud-builders/python"
  #   entrypoint: python
  #   args:
  #     - "app/manage.py"
  #     - "migrate"
  - name: "bash"
    entrypoint: bash
    args:
      - "-c"
      - |
        systemctl restart nginx
        systemctl restart gunicorn