steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/nikhilkotiya/Elevator_problem.git", "."]
  - name: "python"
    entrypoint: python
    args: ["-m", "venv", "venv"]
  - name: "python"
    entrypoint: bash
    args: ["-c", "source venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt"]
  - name: "gcr.io/cloud-builders/bash"
    entrypoint: bash
    args: ["-c", "sudo systemctl restart nginx && sudo systemctl restart gunicorn"]
