# Generated by Django 3.2.5 on 2023-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_app', '0002_auto_20230327_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='is_door_open',
            field=models.BooleanField(default=False),
        ),
    ]
