name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into Google Cloud instance
        uses: appleboy/ssh-action@master
        with:
          host: your-instance-ip
          username: nikhilkotiya8
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/chooserightai/your_project_directory &&
            git pull &&
            source /home/chooserightai/venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            sudo systemctl restart gunicorn &&
            sudo systemctl restart nginx
