name : Deploy to Google Cloud

on:
  push:
    branches:
      - master
  workflow_dispatch:
  manual:
    inputs:
      confirm_deploy:
        description: 'Are you sure you want to deploy?'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into Google Cloud instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.29.206.8
          username: nikhilkotiya8
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            cd /home/chooserightai/Elevator_problem &&
            sudo git pull origin master &&
            source /home/chooserightai/venv/bin/activate &&
            pip install -r requirements.txt &&
            python manage.py migrate &&
            sudo systemctl restart gunicorn &&
            sudo systemctl restart nginx
